name: Python Selenium Tests

on:
  push:
    branches:
      - main      
  pull_request:
    branches:
      - main      

jobs:
  test:
    runs-on: ubuntu-latest  

    services:
      selenium:
        image: selenium/standalone-chrome:latest  
        options: --shm-size 2g  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Set up Python
      uses: actions/setup-python@v2  
      with:
        python-version: '3.8'  

    - name: Install dependencies
      run: |
        pip install selenium  

    - name: Run tests
      run: |
        python -m unittest tests.test_authentication
